[package]
name = "browser"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
rustls = "0.23.29"
tokio = { version = "1.45.1", features = ["full"] }
tokio-rustls = "0.26.2"
webpki-roots = "1.0.2"
